# Generated by Django 6.1 on 2026-08-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('decommissioned', 'Decommissioned')], default='planned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('speed', models.IntegerField(help_text='Mbps')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('maintenance', 'Maintenance')], default='down', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='components.device')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_interface', to='components.interface')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_interface', to='components.interface')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='components.site'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('name', 'device'), name='the combination of name and device must be unique'),
        ),
    ]
